[[pages]]
path = "pages/time_register.py"
name = "Registro de tiempos"
icon = "â±ï¸"

[[pages]]
path = "pages/global_results.py"
name = "ClasificaciÃ³n general"
icon = "ğŸ†"

[[pages]]
path = "pages/month_results.py"
name = "Resultados del mes"
icon = "ğŸ“…"
